{
	[1] = {
		["AllyID"] = 0,
		["AllyName"] = [[Alliance 1]],
		["IsHuman"] = true,
		["IsRequired"] = true,
		["TeamID"] = 0,
		["TeamName"] = [[Giocatore_1]],
		["Color"] = 16711680,
		["ColorR"] = 0,
		["ColorG"] = 0,
		["ColorB"] = 255,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[2] = {
		["AllyID"] = 1,
		["AllyName"] = [[Alliance 2]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 1,
		["TeamName"] = [[Asiatic Legion alfa]],
		["Color"] = 255,
		["ColorR"] = 255,
		["ColorG"] = 0,
		["ColorB"] = 0,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[3] = {
		["AllyID"] = 0,
		["AllyName"] = [[Alliance 1]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 2,
		["TeamName"] = [[Giocatore_2]],
		["Color"] = 16776960,
		["ColorR"] = 0,
		["ColorG"] = 255,
		["ColorB"] = 255,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[4] = {
		["AllyID"] = 0,
		["AllyName"] = [[Alliance 1]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 3,
		["TeamName"] = [[EU Force]],
		["Color"] = 65280,
		["ColorR"] = 0,
		["ColorG"] = 255,
		["ColorB"] = 0,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[5] = {
		["AllyID"] = 1,
		["AllyName"] = [[Alliance 2]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 4,
		["TeamName"] = [[Asiatic Legion bravo]],
		["Color"] = 65535,
		["ColorR"] = 255,
		["ColorG"] = 255,
		["ColorB"] = 0,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[6] = {
		["AllyID"] = 1,
		["AllyName"] = [[Alliance 2]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 5,
		["TeamName"] = [[Asiatic Legion charlie]],
		["Color"] = 16711935,
		["ColorR"] = 255,
		["ColorG"] = 0,
		["ColorB"] = 255,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
}