return {
	corfink = {
		acceleration = 0.2,
		brakerate = 0.0125,
		buildcostenergy = 1460,
		buildcostmetal = 28,
		builder = false,
		buildpic = "nfafink.png",
		buildtime = 2156,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MOBILE NOTLAND ANTIGATOR NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP",
		collide = false,
		cruisealt = 200,
		defaultmissiontype = "VTOL_standby",
		description = "Scout Plane",
		energymake = 0.2,
		energystorage = 0,
		energyuse = 0.2,
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maneuverleashlength = 1280,
		mass = 26,
		maxdamage = 90,
		maxslope = 10,
		maxvelocity = 12.65,
		maxwaterdepth = 0,
		metalstorage = 0,
		mobilestandorders = 1,
		name = "Fink",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "nfafink.s3o",
		radardistance = 1120,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		selfdestructcountdown = 1,
		side = "NFA",
		sightdistance = 835,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 8.349,
		turnrate = 770,
		unitname = "nfafink.s3o",
		workertime = 0,
		customparams = {
			buildpic = "CORFINK.png",
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
