-- made by DaRyL - www.warmachinesrts.com
return {

-----------------------------------------------------------
--- UNITS FEATURES
-----------------------------------------------------------
  coreter= {
               acceleration = 0.0407,
               activatewhenbuilt = true,
--               badTargetCategory = MOBILE,
               brakerate  = 0.0198,
               buildcostenergy = 1757,
               buildcostmetal = 100,
               builder = false,
               buildpic = "nfaeter.png",
               buildtime  = 6404,
               canAttack = false,
               canGuard = true,
               canmove = true,
               canPatrol = true,
--               canstop = 1,
               category = "ALL TANK MOBILE NOTSUB NOWEAPON NOTSHIP NOTAIR SURFACE",
               --collisionvolumeoffsets = "",
               --collisionvolumescales = "",
               --collisionvolumetype = "",
               corpse = "coreter_dead",
--               defaultmissiontype = Standby,
               description = "Radar Jammer Vehicle",
               energymake = 0,
               energystorage = 0,
               energyUse = 100,
               explodeas = "SMALL_UNITEX",
               footprintx = 3,
               footprintz = 3,
	       icontype = "veicoli",
               idleautoheal = 5,
               idletime = 1800,
--               maneuverleashlength  = 640,
               mass = 200,
               maxdamage = 520,
               maxslope = 16,
               maxvelocity = 1.452,
               maxwaterdepth = 0,
               metalStorage = 0,
--               mobilestandorders= 1,
               movementclass = "TANK3",
               name = "Deleter",
               noAutoFire = false,
               nochasecategory = "MOBILE",
               objectname = "nfaeter.s3o",
               onoffable = true,
               radarDistanceJam = 450,
               seismicsignature = 0,
               selfdestructas = "SMALL_UNIT",
               sightdistance = 299,
--               soundcategory= "CORE_VJAM",
--               steeringmode= 1,
--               standingmoveorder = 1,
               TEDClass = "TANK", -- verificare se necessario
               turnrate = 619.3,
               workertime = 0,
               leaveTracks = true,
               trackOffset = 3,
               trackStrength = 6,
               trackStretch = 1,
               trackType = "StdTank",
               trackWidth = 27,
-----------------------------------------------------------
--- Units wreckage and heaps
-----------------------------------------------------------
featuredefs = {
  dead = {
               world = "All Worlds",
               description = "Deleter Wreckage",
               category = "corpses",
               object = "CORETER_DEAD",
               featuredead = "coreter_heap",
               featurereclamate = "SMUDGE01",
               footprintx = 3,
               footprintz = 3,
               height = 20,
               blocking= true,
               hitdensity = 100,
               metal = 65,
               damage = 312,
               reclaimable = true,
               seqnamereclamate = "TREE1RECLAMATE",
               energy = 0,
				collisionvolumeoffsets = "0.0 -1.2425585791 1.2922744751",
				collisionvolumescales = "30.0 14.3981628418 32.5845489502",
				collisionvolumetype = "Box",
               },  -- Close Dead Features
  heap = {
               world = "All Worlds",
               description = "Deleter Heap",
               category = "heaps",
               object = "3X3F",
               footprintx = 3,
               footprintz = 3,
               height = 4,
               blocking = false,
               hitdensity= 100,
               metal = 26,
               damage = 156,
               reclaimable = true,
               featurereclamate = "SMUDGE01",
               seqnamereclamate = "TREE1RECLAMATE",
               energy = 0,
               collisionvolumescales = "55.0 4.0 6.0",
               collisionvolumetype = "cylY",
               },  -- Close heap
},  --  Close Features
-----------------------------------------------------------
--- UNITS SOUND
-----------------------------------------------------------
               sounds = {
               count = {
                     [1] =  "count6",
                     [2] =  "count5",
                     [3] =  "count4",
                     [4] =  "count3",
                     [5] =  "count2",
                     [6] =  "count1",
                       },
               canceldestruct = "cancel2",
               cant = {
                     [1] = "cantdo4",
                      },
               ok = {
                     [1] = "vcormove",
                    },
               select = {
                     [1] = "radjam2",
                        },
               underattack = "warning1",
               },
               }, 
               }
