[core]
name: nfasumo
displayText: Hvy Kbot
displayDescription:"""
- Can attack land units only.\n
- Moves a bit slow.
"""
maxHp: 280
mass: 2000
price: 180
class: CustomUnitMetadata

techLevel: 2

radius: 30

builtFrom_1_name: landFactory
builtFrom_1_pos: 1

builtFrom_2_name: mechFactoryT2
builtFrom_2_pos: 6

[graphics]
total_frames: 1

image: sumobody.png
image_wreak: sumo_wreak.png
image_turret: sumoturret.png

image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2

dustEffect: true

[attack]
canAttack: true
canAttackLandUnits: true
canAttackFlyingUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 200
shootDelay: 60

[leg_1]
x: -8
y: 0
attach_x: -3
attach_y: 0
moveSpeed: 2.2

rotateSpeed: 7

heightSpeed: 0.8
resetAngle:25

image_leg:  leg.png
image_foot: sumofoot1.png

#draw_foot_on_top: true
dust_effect: false

holdDisMin: 11
holdDisMax: 26

[turret_1]
x: 0
y: -5
turnSpeed: 1
turnSpeedAcceleration: 0.04
projectile: 1

size: 32

shoot_flame: resourcePoolSmoke
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.7
shoot_light: yellow

recoilOffset: -1
recoilOutTime: 4
recoilReturnTime: 20


[projectile_1]
life: 300
directDamage: 210
frame: 9
drawSize: 0.8
speed: 9
largeHitEffect: true

[movement]
movementType: LAND

moveSpeed: 1
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.03

maxTurnSpeed: 1
turnAcceleration: 0.06