return {
  treno_locomotiva_feature =
  {
    description = "A train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 25,
    footprintz = 5,
    object = "treno_locomotiva_180.s3o",
    reclaimable = false,
    upright = true,
    collisionvolumeoffsets = "0 40 0",
    collisionvolumescales = "370 120 100",
    collisionvolumetype = "Box",
  },

  treno_vagone_aperto_feature =
  {
    description = "A train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 25,
    footprintz = 5,
    object = "treno_vagone_aperto.s3o",
    reclaimable = false,
    upright = true,
    collisionvolumeoffsets = "0 40 0",
    collisionvolumescales = "370 120 100",
    collisionvolumetype = "Box",
  },

  treno_vagone_chiuso_feature =
  {
    description = "A train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 25,
    footprintz = 5,
    object = "treno_vagone_chiuso.s3o",
    reclaimable = false,
    upright = true,
    collisionvolumeoffsets = "0 40 0",
    collisionvolumescales = "370 120 100",
    collisionvolumetype = "Box",
  },

  treno_vagone_container_feature =
  {
    description = "A train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 25,
    footprintz = 5,
    object = "treno_vagone_container.s3o",
    reclaimable = false,
    upright = true,
    collisionvolumeoffsets = "0 40 0",
    collisionvolumescales = "370 120 100",
    collisionvolumetype = "Box",
  },

  treno_rotto1_feature =
  {
    description = "A destroyed train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 5,
    footprintz = 5,
    object = "treno_rotto_1.s3o",
    reclaimable = false,
    upright = true,
    collisionvolumeoffsets = "0 10 0",
    collisionvolumescales = "110 100 100",
    collisionvolumetype = "Box",
  },

  treno_rotto2_feature =
  {
    description = "A destroyed train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 5,
    footprintz = 5,
    object = "treno_rotto_2.s3o",
    reclaimable = false,
    upright = true,
    collisionvolumeoffsets = "0 10 0",
    collisionvolumescales = "110 100 100",
    collisionvolumetype = "Box",
  },

  treno_rotto3_feature =
  {
    description = "A destroyed train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 5,
    footprintz = 5,
    object = "treno_rotto_3.s3o",
    reclaimable = false,
    upright = true,    
    collisionvolumeoffsets = "0 10 0",
    collisionvolumescales = "110 100 100",
    collisionvolumetype = "Box",
  },

  treno_rotto4_feature =
  {
    description = "A destroyed train",
    blocking = true,
    damage = 100000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
    indestructible = true,
    noselect = false,
    metal = 25000,
    footprintx = 5,
    footprintz = 5,
    object = "treno_rotto_4.s3o",
    reclaimable = false,
    upright = true,    
    collisionvolumeoffsets = "0 10 0",
    collisionvolumescales = "110 100 100",
    collisionvolumetype = "Box",
  },

}