return {
  asteroide03_feature =
  {
    description = "An asteroid",
    blocking = true,
    damage = 5000,
    energy = 0,
    flammable = false,
--    featureDead ="pala002d_feature",
    noselect = false,
    metal = 2500,
    footprintx = 11,
    footprintz = 14,
    object = "asteroide03.s3o",
    reclaimable = true,
    upright = true,
    crushResistance = 10000,
    crushResistance = 10000,
--    collisionvolumeoffsets = "0 50 0",
--    collisionvolumescales = "70 100 70",
--    collisionvolumetype = "Box",
  },

  pala002d_feature =
  {
    description = "A destroyed building",
    blocking = true,
    damage = 500,
    energy = 0,
    flammable = false,
--    featureDead ="Pala002_d",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "pala002_d.s3o",
    reclaimable = true,
    upright = true,
    crushResistance = 10000,
    collisionvolumeoffsets = "0 35 0",
    collisionvolumescales = "70 70 70",
    collisionvolumetype = "Box",
  },
}