return {
  bigrock001_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock001_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  bigrock002_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock002_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  bigrock003_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock003_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  bigrock004_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock004_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
  
    bigrock005_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock005_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock006_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock006_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock007_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock007_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock008_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock008_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock009_lunar_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock009_lunar_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
}



