return {
  bigrock001_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock001_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  bigrock002_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock002_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  bigrock003_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock003_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  bigrock004_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock004_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
  
    bigrock005_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock005_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock006_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock006_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock007_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock007_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock008_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock008_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
    bigrock009_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 70000,
    energy = 0,
    flammable = false,
    indestructible = true,
--    featureDead ="",
    noselect = true,
    metal = 100,
    footprintx = 10,
    footprintz = 10,
    object = "bigrock009_feature.s3o",
    reclaimable = false,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  
}



