return {
  cumulo_1_feature =
  {
    description = "A lava pile",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 70,
    footprintx = 1,
    footprintz = 1,
    object = "cumulo_1.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  cumulo_2_feature =
  {
    description = "A lava pile",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 70,
    footprintx = 1,
    footprintz = 1,
    object = "cumulo_2.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  cumulo_3_feature =
  {
    description = "A lava pile",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 70,
    footprintx = 1,
    footprintz = 1,
    object = "cumulo_3.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  cumulo_4_feature =
  {
    description = "A lava pile",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 70,
    footprintx = 1,
    footprintz = 1,
    object = "cumulo_4.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  cumulo_5_feature =
  {
    description = "A lava pile",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 70,
    footprintx = 1,
    footprintz = 1,
    object = "cumulo_5.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  cumulo_6_feature =
  {
    description = "A lava pile",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 70,
    footprintx = 1,
    footprintz = 1,
    object = "cumulo_6.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
}