return {
eridlon_bridge1_feature =
  {
    description = "A broken bridge",
    blocking = true,
    damage = 5000,
    energy = 2500,
    flammable = false,
--    featureDead ="Station_one_antenna_feature_dead",
    noselect = false,
    metal = 1000,
    footprintx = 1,
    footprintz = 1,
    object = "bridge_destroy.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

eridlon_bridge2_feature =
  {
    description = "A broken bridge",
    blocking = true,
    damage = 5000,
    energy = 2500,
    flammable = false,
--    featureDead ="Station_one_antenna_feature_dead",
    noselect = false,
    metal = 1000,
    footprintx = 1,
    footprintz = 1,
    object = "bridge_destroy2.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
}