return {
  fabbrica_feature_1 =
  {
    description = "A factory",
    blocking = true,
    damage = 1000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
--    noselect = true,
    metal = 250,
    footprintx = 1,
    footprintz = 1,
    object = "fabbrica_1.s3o",
    reclaimable = true,
    upright = true,
    crushResistance = 10000,
    collisionvolumeoffsets = "0 25 0",
    collisionvolumescales = "70 50 70",
    collisionvolumetype = "Box",
  },


  fabbrica_feature_3 =
  {
    description = "A factory",
    blocking = true,
    damage = 1000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
--    noselect = true,
    metal = 250,
    footprintx = 1,
    footprintz = 1,
    object = "fabbrica_3.s3o",
    reclaimable = true,
    upright = true,
    crushResistance = 10000,
    collisionvolumeoffsets = "0 25 0",
    collisionvolumescales = "70 50 140",
    collisionvolumetype = "Box",
  },

  fabbrica_feature_3_bis =
  {
    description = "A factory",
    blocking = true,
    damage = 1000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
--    noselect = true,
    metal = 250,
    footprintx = 1,
    footprintz = 1,
    object = "fabbrica_3_bis.s3o",
    reclaimable = true,
    upright = true,
    crushResistance = 10000,
    collisionvolumeoffsets = "0 25 0",
    collisionvolumescales = "150 50 150",
    collisionvolumetype = "Box",
  },

 fabbrica_feature_4 =
  {
    description = "A factory",
    blocking = true,
    damage = 1000,
    energy = 0,
    flammable = false,
--    featureDead ="pala001d_feature",
--    noselect = true,
    metal = 250,
    footprintx = 1,
    footprintz = 1,
    object = "fabbrica_4.s3o",
    reclaimable = true,
    upright = true,
    crushResistance = 10000,
    collisionvolumeoffsets = "0 50 0",
    collisionvolumescales = "140 100 170",
    collisionvolumetype = "Box",
  },

}