return {
  heavy_transporter_destroyed_front =
  {
    description = "EUF Heavy transporter destroyed",
    blocking = true,
    damage = 30000,
    energy = 60000,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 10000,
    footprintx = 5,
    footprintz = 5,
    object = "EUF_hvytranspcontainer_destroyed_front.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  heavy_transporter_destroyed_rear =
  {
    description = "EUF Heavy transporter destroyed",
    blocking = true,
    damage = 15000,
    energy = 30000,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 5000,
    footprintx = 5,
    footprintz = 5,
    object = "EUF_hvytranspcontainer_destroyed_rear.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
}