return {
  livrium00_feature =
  {
    description = "A livrium crystal",
    blocking = false,
    damage = 1000,
    energy = 0,
    flammable = false,
--    featureDead ="pala002d_feature",
    noselect = true,
    metal = 350,
    footprintx = 1,
    footprintz = 1,
    object = "livrium00.s3o",
    reclaimable = false,
    upright = true,
    crushResistance = 10000,
    collisionvolumeoffsets = "0 2 0",
    collisionvolumescales = "35 4 35",
    collisionvolumetype = "Box",
  },
  livrium00_chiaro_feature =
  {
    description = "A livrium crystal",
    blocking = false,
    damage = 1000,
    energy = 0,
    flammable = false,
--    featureDead ="pala002d_feature",
    noselect = true,
    metal = 350,
    footprintx = 1,
    footprintz = 1,
    object = "livrium00_chiaro.s3o",
    reclaimable = false,
    upright = true,
    crushResistance = 10000,
    collisionvolumeoffsets = "0 2 0",
    collisionvolumescales = "35 4 35",
    collisionvolumetype = "Box",
  },
}