return {
  pinesnow002_feature =
  {
    description = "A pine",
    blocking = true,
    damage = 200,
    energy = 50,
    flammable = true,
--    featureDead ="",
    noselect = false,
    metal = 0,
    footprintx = 1,
    footprintz = 1,
    object = "pino2.s3o",
    reclaimable = true,
    upright = false,
    collisionvolumeoffsets = "0 0 0",
    collisionvolumescales = "5 50 5",
    collisionvolumetype = "Box",
  },
  pinespring002_feature =
  {
    description = "A pine",
    blocking = true,
    damage = 200,
    energy = 50,
    flammable = true,
--    featureDead ="",
    noselect = false,
    metal = 0,
    footprintx = 1,
    footprintz = 1,
    object = "pino2_primavera.s3o",
    reclaimable = true,
    upright = false,
    collisionvolumeoffsets = "0 0 0",
    collisionvolumescales = "5 50 5",
    collisionvolumetype = "Box",
  },
}