return {
  rocklunar001_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "rocklunar001.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  rocklunar002_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "rocklunar002.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  rocklunar003_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "rocklunar003.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  rocklunar004_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "rocklunar004.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },


}