return {
  Station_one_antenna_small_no_feature =
  {
    description = "An antenna",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_antenna_small_no_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_no.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_antenna_small_no_feature_dead =
  {
    description = "Wreckage of an antenna",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = true,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_rottami_no.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },


 Station_one_antenna_small_ne_feature =
  {
    description = "An antenna",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_antenna_small_ne_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_ne.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_antenna_small_ne_feature_dead =
  {
    description = "Wreckage of an antenna",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_rottami_ne.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },



 Station_one_antenna_small_se_feature =
  {
    description = "An antenna",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_antenna_small_se_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_se.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_antenna_small_se_feature_dead =
  {
    description = "Wreckage of an antenna",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_rottami_se.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

 Station_one_antenna_small_so_feature =
  {
    description = "An antenna",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_antenna_small_so_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_so.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_antenna_small_so_feature_dead =
  {
    description = "Wreckage of an antenna",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_antenna_small_rottami_so.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
}