return {
  Station_one_scudi_o_feature =
  {
    description = "A shield",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_scudi_o_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_o.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_scudi_o_feature_dead =
  {
    description = "Wreckage of a shield",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_rottami_o.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_scudi_n_feature =
  {
    description = "A shield",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_scudi_n_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_n.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_scudi_n_feature_dead =
  {
    description = "Wreckage of a shield",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_rottami_n.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_scudi_s_feature =
  {
    description = "A shield",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_scudi_s_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_s.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_scudi_s_feature_dead =
  {
    description = "Wreckage of a shield",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_rottami_s.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },


  Station_one_scudi_e_feature =
  {
    description = "A shield",
    blocking = true,
    damage = 6000,
    energy = 3000,
    flammable = false,
    featureDead ="Station_one_scudi_e_feature_dead",
    noselect = false,
    metal = 1500,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_e.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
  Station_one_scudi_e_feature_dead =
  {
    description = "Wreckage of a shield",
    blocking = true,
    damage = 3000,
    energy = 1500,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 750,
    footprintx = 1,
    footprintz = 1,
    object = "Station_one_scudi_rottami_e.s3o",
    reclaimable = true,
    upright = true,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },
}