return {
  therock001_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_1.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  therock002_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_2.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  therock003_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_3.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  therock004_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_4.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  therock005_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_5.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  therock006_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_6.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  therock007_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_7.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

  therock008_feature =
  {
    description = "A rock",
    blocking = true,
    damage = 700,
    energy = 0,
    flammable = false,
--    featureDead ="",
    noselect = false,
    metal = 100,
    footprintx = 1,
    footprintz = 1,
    object = "therock_8.s3o",
    reclaimable = true,
    upright = false,
--    collisionvolumeoffsets = "0 0 0",
--    collisionvolumescales = "5 50 5",
--    collisionvolumetype = "Box",
  },

}